# Generated by Django 5.1.1 on 2025-01-16 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('faculty_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('faculty_name', models.CharField(max_length=255)),
                ('Phone', models.CharField(blank=True, max_length=255, null=True)),
                ('Email', models.EmailField(blank=True, max_length=255, null=True)),
                ('Address', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=255)),
                ('credits', models.IntegerField()),
                ('theory_hours', models.IntegerField()),
                ('practice_hours', models.IntegerField()),
                ('project_hours', models.IntegerField(default=0)),
                ('prerequisites', models.ManyToManyField(blank=True, related_name='prerequisite_for', to='trainingprogram.course')),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('major_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('major_name', models.CharField(max_length=255)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingprogram.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingProgram',
            fields=[
                ('program_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('program_name', models.CharField(max_length=255)),
                ('StartYear', models.IntegerField()),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingprogram.major')),
            ],
        ),
        migrations.CreateModel(
            name='OptionalGroup',
            fields=[
                ('course_type', models.IntegerField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optional_groups', to='trainingprogram.course')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optional_groups', to='trainingprogram.trainingprogram')),
            ],
        ),
        migrations.CreateModel(
            name='CourseTrainingProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField()),
                ('course_type', models.IntegerField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')])),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingprogram.course')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingprogram.trainingprogram')),
            ],
        ),
    ]
