# Generated by Django 5.1.1 on 2025-01-12 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=255)),
                ('credits', models.IntegerField()),
                ('theory_hours', models.IntegerField()),
                ('practice_hours', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TrainingProgram',
            fields=[
                ('program_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('program_name', models.CharField(max_length=255)),
                ('StartYear', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CourseTrainingProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField()),
                ('course_type', models.CharField(max_length=255)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingprogram.course')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingprogram.trainingprogram')),
            ],
        ),
    ]
