# Generated by Django 5.1.3 on 2025-05-11 08:46

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('ClassID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('Classroom', models.CharField(max_length=255)),
                ('AcademyYear', models.CharField(max_length=255)),
                ('Semester', models.CharField(max_length=255)),
                ('LecturerID', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('faculty_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('faculty_name', models.CharField(max_length=255)),
                ('Phone', models.CharField(blank=True, max_length=255, null=True)),
                ('Email', models.EmailField(blank=True, max_length=255, null=True)),
                ('Address', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OptionalGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('course_type', models.IntegerField()),
                ('group_name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('min_credits', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('RoleID', models.BigAutoField(primary_key=True, serialize=False)),
                ('RoleName', models.CharField(max_length=255)),
                ('Create_at', models.DateField(auto_now_add=True)),
                ('Update_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('ID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('SemesterName', models.CharField(max_length=255)),
                ('StartDate', models.DateField(null=True)),
                ('EndDate', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('ScheduleID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('Date', models.DateField()),
                ('StartTime', models.TimeField()),
                ('EndTime', models.TimeField()),
                ('Classroom', models.CharField(max_length=255)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingprogram.class')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=255)),
                ('credits', models.IntegerField()),
                ('theory_hours', models.IntegerField()),
                ('practice_hours', models.IntegerField()),
                ('project_hours', models.IntegerField(default=0)),
                ('prerequisites', models.ManyToManyField(blank=True, related_name='prerequisite_for', to='trainingprogram.course')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingprogram.course'),
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('EnrollmentID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('EnrollDate', models.DateField()),
                ('Status', models.CharField(choices=[('Da Dang Ky', 'Đã đăng ký'), ('Dang Cho Duyet', 'Đang chờ duyệt'), ('Da Huy Dang Ky', 'Đã hủy đăng ký'), ('Dang Huy Dang Ky', 'Đang hủy đăng ký')], max_length=20)),
                ('StudentID', models.CharField(max_length=255)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingprogram.class')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('UserID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('img_url', models.CharField(blank=True, max_length=255, null=True)),
                ('Create_at', models.DateField(auto_now_add=True)),
                ('Update_at', models.DateField(auto_now=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trainingprogram.faculty')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('LecturerID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Expertise', models.CharField(max_length=255)),
                ('AcademicTitle', models.CharField(max_length=255)),
                ('Fullname', models.CharField(max_length=255)),
                ('Email', models.CharField(max_length=255)),
                ('Phone', models.CharField(max_length=255)),
                ('Gender', models.CharField(max_length=255)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingprogram.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('major_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('major_name', models.CharField(max_length=255)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingprogram.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationHistory',
            fields=[
                ('HistoryID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('TimeStamp', models.TimeField()),
                ('Action', models.CharField(choices=[('Dang Ky', 'Đăng ký'), ('Huy Dang Ky', 'Hủy đăng ký')], max_length=20)),
                ('StudentID', models.CharField(max_length=255)),
                ('ClassID', models.CharField(max_length=255)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingprogram.enrollment')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('StudentID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('AcademicYear', models.CharField(max_length=255, null=True)),
                ('Class', models.CharField(max_length=255, null=True)),
                ('Fullname', models.CharField(max_length=255, null=True)),
                ('Dob', models.DateField(null=True)),
                ('Gender', models.CharField(max_length=255, null=True)),
                ('Address', models.CharField(max_length=255, null=True)),
                ('Email', models.CharField(max_length=255, null=True)),
                ('Phone', models.CharField(max_length=255, null=True)),
                ('major', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trainingprogram.major')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('GradeID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ContinuosAssScore', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('FinalExamScore', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('Result', models.CharField(max_length=255, null=True)),
                ('Semester', models.CharField(max_length=255, null=True)),
                ('AcademyYear', models.CharField(max_length=255, null=True)),
                ('TestTime', models.CharField(max_length=255, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingprogram.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingprogram.student')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluate',
            fields=[
                ('ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('TrainingPoint', models.IntegerField()),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingprogram.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingprogram.student')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingProgram',
            fields=[
                ('program_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('program_name', models.CharField(max_length=255)),
                ('StartYear', models.IntegerField()),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingprogram.major')),
            ],
        ),
        migrations.CreateModel(
            name='CourseTrainingProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField()),
                ('course_type', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9')])),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_for', to='trainingprogram.course')),
                ('option_G', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='belongto_CourseTrainingProgram', to='trainingprogram.optionalgroup')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_for', to='trainingprogram.trainingprogram')),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RoleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingprogram.role')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('UserID', 'RoleID')},
            },
        ),
    ]
