# Generated by Django 5.1.3 on 2025-05-11 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingprogram', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursetrainingprogram',
            name='option_G',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='belongto_CourseTrainingProgram', to='trainingprogram.optionalgroup'),
        ),
    ]
