# Generated by Django 5.1.1 on 2025-01-12 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingprogram', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, related_name='prerequisite_for', to='trainingprogram.course'),
        ),
        migrations.AlterField(
            model_name='coursetrainingprogram',
            name='course_type',
            field=models.CharField(choices=[('Compulsory', 'Compulsory'), ('Optional', 'Optional')], max_length=50),
        ),
    ]
