# Generated by Django 5.1.1 on 2025-02-06 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingprogram', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('RoleID', models.BigAutoField(primary_key=True, serialize=False)),
                ('RoleName', models.CharField(max_length=255)),
                ('Create_at', models.DateField(auto_now_add=True)),
                ('Update_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('LecturerID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('Expertise', models.CharField(max_length=255)),
                ('AcademicTitle', models.CharField(max_length=255)),
                ('Fullname', models.CharField(max_length=255)),
                ('Email', models.CharField(max_length=255)),
                ('Phone', models.CharField(max_length=255)),
                ('Gender', models.CharField(max_length=255)),
                ('faculty_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingprogram.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('StudentID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('AcademicYear', models.CharField(max_length=255)),
                ('Class', models.CharField(max_length=255)),
                ('Fullname', models.CharField(max_length=255)),
                ('Dob', models.DateField()),
                ('Gender', models.CharField(max_length=255)),
                ('Address', models.CharField(max_length=255)),
                ('Email', models.CharField(max_length=255)),
                ('Phone', models.CharField(max_length=255)),
                ('major_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingprogram.major')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('img_url', models.CharField(blank=True, max_length=255, null=True)),
                ('Create_at', models.DateField(auto_now_add=True)),
                ('Update_at', models.DateField(auto_now=True)),
                ('LecturerID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trainingprogram.lecturer')),
                ('StudentID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trainingprogram.student')),
                ('faculty_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trainingprogram.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RoleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingprogram.role')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingprogram.user')),
            ],
            options={
                'unique_together': {('UserID', 'RoleID')},
            },
        ),
    ]
