# Generated by Django 5.1.1 on 2025-01-15 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingprogram', '0002_course_prerequisites_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='project_hours',
            field=models.IntegerField(default=0),
        ),
    ]
