# Generated by Django 5.1.3 on 2025-05-28 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingprogram', '0002_alter_coursetrainingprogram_option_g'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='StudentCode',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
