# Generated by Django 5.1.6 on 2025-03-02 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainingprogram", "0002_user_groups_user_is_active_user_is_staff_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
