# Generated by Django 5.1.1 on 2025-02-06 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainingprogram', '0002_role_lecturer_student_user_userrole'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecturer',
            old_name='faculty_id',
            new_name='faculty',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='major_id',
            new_name='major',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='faculty_id',
            new_name='faculty',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='LecturerID',
            new_name='lecturer',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='StudentID',
            new_name='student',
        ),
    ]
