# Generated by Django 5.1.6 on 2025-03-02 18:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainingprogram", "0003_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="UserID",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
