# Generated by Django 5.1.1 on 2025-01-15 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingprogram', '0003_course_project_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursetrainingprogram',
            name='course_type',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], max_length=50),
        ),
    ]
