# Generated by Django 5.1.1 on 2025-02-07 15:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingprogram', '0003_rename_faculty_id_lecturer_faculty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('ClassID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('Classroom', models.CharField(max_length=255)),
                ('AcademyYear', models.CharField(max_length=255)),
                ('Semester', models.CharField(max_length=255)),
                ('LecturerID', models.CharField(max_length=255)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingprogram.course')),
            ],
        ),
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('ScheduleID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('Date', models.DateField()),
                ('StartTime', models.TimeField()),
                ('EndTime', models.TimeField()),
                ('Classroom', models.CharField(max_length=255)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingprogram.class')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('EnrollmentID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('EnrollDate', models.DateField()),
                ('Status', models.CharField(choices=[('Da Dang Ky', 'Đã đăng ký'), ('Dang Cho Duyet', 'Đang chờ duyệt'), ('Da Huy Dang Ky', 'Đã hủy đăng ký'), ('Dang Huy Dang Ky', 'Đang hủy đăng ký')], max_length=20)),
                ('StudentID', models.CharField(max_length=255)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingprogram.class')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('GradeID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('ContinuosAssScore', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('FinalExamScore', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('Result', models.CharField(max_length=255)),
                ('Semester', models.CharField(max_length=255)),
                ('AcademyYear', models.CharField(max_length=255)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingprogram.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingprogram.student')),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationHistory',
            fields=[
                ('HistoryID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('TimeStamp', models.TimeField()),
                ('Action', models.CharField(choices=[('Dang Ky', 'Đăng ký'), ('Huy Dang Ky', 'Hủy đăng ký')], max_length=20)),
                ('StudentID', models.CharField(max_length=255)),
                ('ClassID', models.CharField(max_length=255)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingprogram.enrollment')),
            ],
        ),
    ]
