# Generated by Django 5.1.6 on 2025-03-04 14:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainingprogram", "0004_alter_user_userid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lecturer",
            name="LecturerID",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="StudentID",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
