# Generated by Django 5.1.6 on 2025-03-04 14:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainingprogram", "0005_alter_lecturer_lecturerid_alter_student_studentid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faculty",
            name="faculty_id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
