# Generated by Django 5.1.6 on 2025-03-06 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainingprogram", "0006_alter_faculty_faculty_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faculty",
            name="faculty_id",
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
