# Generated by Django 5.1.6 on 2025-03-06 17:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainingprogram", "0007_alter_faculty_faculty_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grade",
            name="GradeID",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
