# Generated by Django 5.1.6 on 2025-03-07 14:13

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainingprogram", "0008_alter_grade_gradeid"),
    ]

    operations = [
        migrations.CreateModel(
            name="Semester",
            fields=[
                (
                    "ID",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("SemesterName", models.CharField(max_length=255)),
                ("StartDate", models.DateField(null=True)),
                ("EndDate", models.DateField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name="grade",
            name="TestTime",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="grade",
            name="AcademyYear",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="grade",
            name="ContinuosAssScore",
            field=models.FloatField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(10.0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="grade",
            name="FinalExamScore",
            field=models.FloatField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(10.0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="grade",
            name="Result",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="grade",
            name="Semester",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name="Evaluate",
            fields=[
                (
                    "ID",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("TrainingPoint", models.IntegerField()),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="trainingprogram.student",
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="trainingprogram.semester",
                    ),
                ),
            ],
        ),
    ]
