# Generated by Django 5.1.6 on 2025-03-10 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "trainingprogram",
            "0009_semester_grade_testtime_alter_grade_academyyear_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="lecturer",
        ),
        migrations.RemoveField(
            model_name="user",
            name="student",
        ),
        migrations.AddField(
            model_name="student",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
