# Generated by Django 5.1.6 on 2025-03-10 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainingprogram", "0010_remove_user_lecturer_remove_user_student_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="AcademicYear",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="Address",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="Class",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="Dob",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="Email",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="Fullname",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="Gender",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="Phone",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
