# Generated by Django 5.1.6 on 2025-03-10 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "trainingprogram",
            "0011_alter_student_academicyear_alter_student_address_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="major",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="trainingprogram.major",
            ),
        ),
    ]
