# Generated by Django 5.1.3 on 2025-04-12 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingprogram', '0012_alter_student_major'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionalgroup',
            name='min_credits',
            field=models.IntegerField(null=True),
        ),
    ]
