# Generated by Django 5.1.3 on 2025-04-24 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingprogram', '0013_optionalgroup_min_credits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursetrainingprogram',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_for', to='trainingprogram.course'),
        ),
        migrations.AlterField(
            model_name='coursetrainingprogram',
            name='course_type',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9')]),
        ),
        migrations.AlterField(
            model_name='coursetrainingprogram',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_for', to='trainingprogram.trainingprogram'),
        ),
    ]
